import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  compileNoirSource,
  createProof,
  verifyProof,
} from "../utils/compile_prove_verify";

const CIRCUIT_PATH = new URL("../../proofs/circuits/src/main.nr", import.meta.url).href;

let inputs = {
  puzzle: [1,2, 1, 2],
  user_input: [1,2, 1, 2],
};

export async function execute_procedure() {

  const cir = await fetch(CIRCUIT_PATH);
  const tex = await cir.text();

  const compiled_noir = await compileNoirSource(tex);

  const { verifier, proof} : { verifier: any, proof: Uint8Array }= await createProof(compiled_noir, inputs);

  console.log("starting verify with proof",  Array.from(proof).map(b => b.toString(16)))
  const bytes = Array.from(proof).map(a => a.toString(16)).reduce((prev, curr) => prev + curr);
  console.log("Proof bytes", bytes);

  const verified = await verifyProof(verifier, proof);

  console.log("verified: ", verified);
}

async function prove() {
  execute_procedure();
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <button onClick={prove}>Prove</button>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
