import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import * as fs from 'fs';

/* import initBackend, {
  compute_witnesses,
  serialise_acir_to_barrtenberg_circuit,
} from "@noir-lang/aztec_backend"; */
/* import {
  create_proof,
  verify_proof,
  setup_generic_prover_and_verifier,
  //BarretenbergWasm,
} from "@noir-lang/barretenberg/dest/client_proofs"; */
import initialiseAztecBackend from "@noir-lang/aztec_backend";
import {
  create_proof,
  verify_proof,
  setup_generic_prover_and_verifier,
} from "@noir-lang/barretenberg";
import initNoirWasm, { compile } from "@noir-lang/noir_wasm";
import initialiseResolver from "@noir-lang/noir-source-resolver";

const ACIR_PATH = new URL("../circuits/build/main.acir", import.meta.url).href;
const CIRCUIT_PATH = new URL("../circuits/src/main.nr", import.meta.url).href;

let inputs = {
  puzzle: [1,2, 1, 2],
  user_input: [1,2, 1, 2],
};

async function compileNoirSource(noir_source : any) {
  await initNoirWasm();

  initialiseResolver((id : any) => {

      console.log(`Resolving source ${id}`);

      return noir_source;

  });

  console.log("Compiling Noir source...");

  const compiled_noir = await compile("main.nr");

  console.log("Noir source compilation done.");

  return compiled_noir;
}

async function createProof(compiled_noir : any, circuitParams : any) {

  await initialiseAztecBackend();



  const acir = compiled_noir.circuit;

  console.log("Setting up Prover and Verifier...");

  const [prover, verifier] = await setup_generic_prover_and_verifier(acir);

  console.log("Setting up Prover and Verifier done.");

  console.log("Creating proof...");

  const proof = await create_proof(prover, acir, circuitParams);

  console.log("Creating proof done.");

  return { verifier, proof };
}

export async function execute_procedure() {

  const cir = await fetch(CIRCUIT_PATH);
  const tex = await cir.text();

  const compiled_noir = await compileNoirSource(tex);

 

  const { verifier, proof } = await createProof(compiled_noir, inputs);



  console.log("starting verify")

  const verified = await verify_proof(verifier, proof);

  console.log("verified: ", verified);
}

async function prove() {
  execute_procedure();
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <button onClick={prove}>Prove</button>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
